### ISSUE TITLE
APM Server transport error (ECONNREFUSED): connect ECONNREFUSED 127.0.0.1:8200

### ISSUE THREAD

**Issue by YasiruDev** [elastic/apm-agent-nodejs#1332]
I have installed` apm-server` and setup apm-server.yml as bellow

```
output.elasticsearch:
  hosts: ["localhost:9200"]
  username: "elastic"
  password: "elastic"
```

then run service apm-server start .

configured Node side as bellow

```
var apm = require('elastic-apm-node').start({
    serviceName: 'MyApp',
    serverUrl: 'http://localhost:8200'
  })
```

Checked status

**APM Server status : You have correctly setup APM Server**

**Agent status : Data successfully received from one or more agents**

It's worked last night and showed charts on kibana dashboard.but now i'm getting bellow error on my Console and No services found on dashboard

`[ERROR] APM Server transport error (ECONNREFUSED): connect ECONNREFUSED 127.0.0.1:8200`

Kibana - 7.3.1
apm-server - 7.3.1
elasticsearch - 7.3.1
