### ISSUE TITLE
Serverless offline: context.done called twice within handler

### ISSUE THREAD

**Issue by LucGranato** [elastic/apm-agent-nodejs#1338]
Hello guys!

Using **apm.lambda handler** when running **serverless offline** does not answer any requests.

The following log occurs when I make a call to the localhost server.

```
Serverless: Warning: context.done called twice within handler 'app'!
```

**To Reproduce**

I made a very basic code to show the problem.

**handler.js**

```javascript
'use strict';

const apm = require('elastic-apm-node').start({
    serverUrl: process.env.APM_SERVER_URL,
    secretToken: process.env.APM_SECRET_TOKEN,
    serviceName: 'apm-lambda-express',
});

module.exports.app = apm.lambda(function(event, context, callback) {
  context.callbackWaitsForEmptyEventLoop = false;
  callback(null, 'Hello!');
});
```

**serverless.yml**

```yml
service: apm_lambda_express
provider:
  name: aws
  runtime: nodejs10.x
  environment:
    DEBUG: "*"
    APM_SERVER_URL: "your server url"
    APM_SECRET_TOKEN: "your secret token"

functions:
  app:
    handler: handler.app
    events:
      - http:
          path: "{proxy+}"
          method: any
          cors: true

plugins:
  - serverless-offline
```

**package.json**

```json
{
  "name": "apm_lambda_express",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "dev": "sls offline start"
  },
  "author": "Luca Granato",
  "license": "MIT",
  "dependencies": {
    "elastic-apm-node": "2.16.2"
  },
  "devDependencies": {
    "serverless-offline": "5.10.1"
  }
}
```

**Environment**

- OS: macOS Mojave 10.14.6
- Node.js version: 10.16.3
- APM Server version: 6.8.1
- Agent version: 2.16.2
