### ISSUE TITLE
redis@4.0.0 instrumentation

### ISSUE THREAD

**Issue by trentm** [elastic/apm-agent-nodejs#2477]
https://www.npmjs.com/package/redis/v/4.0.0 was published 2021-11-25. It would be good to add support for it.

Currently in .tav.yml:

```yaml
redis:
  versions: '>=2.0.0 <4.0.0'
  commands: node test/instrumentation/modules/redis.test.js
```

and in modules/redis.js:

```js
module.exports = function (redis, agent, { version, enabled }) {
  if (!semver.satisfies(version, '>=2.0.0 <4.0.0')) {
    agent.logger.debug('redis version %s not supported - aborting...', version)
    return redis
  }
```

Note that dependabot is already suggesting that opbeans-node update to redis@4: https://github.com/elastic/opbeans-node/pull/117
