### ISSUE TITLE
Socket hang up with ExpressJS

### ISSUE THREAD

**Issue by namhq1989** [elastic/apm-agent-nodejs#256]
I've setup my server with `elastic-apm-node`, and it run ok. But after every period of time (30-60 min), it causes an error like below:

```javascript
Error: socket hang up
    at createHangUpError (_http_client.js:331:15)
    at Socket.socketOnEnd (_http_client.js:423:23)
    at emitNone (events.js:111:20)
    at Socket.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1055:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickDomainCallback (internal/process/next_tick.js:218:9)
```

This error made my server down too, so I need to restart it. After removed the code, everthing okay now.
This is my config code:

```javascript
require('elastic-apm-node').start({
  serviceName: '...',
  secretToken: '...',
  instrument: true,
  captureBody: 'all',
  errorOnAbortedRequests: true,
  serverUrl: 'http://...:8200',
  active: process.env.NODE_ENV === 'production'
})
```

Version

```
Elasticsearch, Kibana, APM v6.2.1
NodeJS v8.9.4
ExpressJS v4.15.2
```

I searched for this error, but there's no results with apm-server. Is this a known issue, or my configuration miss something? Please help me to fix this.
Thanks!

**Comment by 7agustibm** [comment]
I had the same problem. I configured APM Server with these values and I solved it.

apm-server.yml:

`apm-server:
  host: 0.0.0.0:8200
  
output.elasticsearch:
  hosts: ['elasticsearch:9200']
`

**Comment by namhq1989** [comment]
Thank you for suggested, but my apm-server.yml config is the same as you mentioned above.

```
apm-server:

  # Defines the host and port the server is listening on
  host: "0.0.0.0:8200"

  # Please be aware that frontend support is an experimental feature at the moment!
  frontend:
    # To enable experimental frontend support set this to true.
    enabled: false

  # Authorization token to be checked. If a token is set here the agents must
  # send their token in the following format: Authorization: Bearer <secret-token>
  secret_token: "..."

  #ssl.enabled: false
  #ssl.certificate : "path/to/cert"
  #ssl.key : "path/to/private_key"

output.elasticsearch:
  # Array of hosts to connect to.
  hosts: ["localhost:9200"]

  # Optional protocol and basic auth credentials.
  #protocol: "https"
  username: "elastic"
  password: "..."
```

This problem only happen in production mode, I tried to simulate random request (0.1-0.5s/request), but my local server running without any errors.
Anyone can help me solve this?
