### ISSUE TITLE
follow-up work for TAV tests now being in GH Actions

### ISSUE THREAD

**Issue by trentm** [elastic/apm-agent-nodejs#3227]
https://github.com/elastic/apm-agent-nodejs/pull/3127 moved our TAV tests CI runs from Jenkins to GH Actions. There are a few things to follow-up on with this:

- [x] I would very much like a way to be able to *manually* run a subset of the TAV tests on a PR. I *can* manually run one or more `.ci/scripts/test.sh -b "release" -t "${{ module }}" "${{node }}"` on my dev machine. However, it is useful to have check results reflected on a PR. Also for community PRs it is nice to run relevant TAV tests and have the results available via the PR. Before, when using Jenkins, we had the `run module tests for <modules>` GH comment. It doesn't need to be a GitHub comment. See https://github.com/elastic/apm-agent-nodejs/pull/3127#issuecomment-1487192295 for earlier discussion on this.
- [x] Are the individual TAV job checks shown for commits on main?  For example [commit 6660cc3](https://github.com/elastic/apm-agent-nodejs/commit/6660cc3d05eb351947518571c1e7e5078bab0a52) is the commit that added the new workflow, its workflow *did* run last night (https://github.com/elastic/apm-agent-nodejs/actions/runs/4552294471), yet the summary of checks for that commit do *not* include the TAV job runs.
- [x] Some sort of lint checks on tav.yml would be worthwhile:
    - [x] Is the [set of modules](https://github.com/elastic/apm-agent-nodejs/blob/main/.github/workflows/tav.yml#L38-L73) up to date? This should match the full set of `.tav.yml` module/group names for all ".tav.yml" files in the repo (currently there are two).
    - [x] Does number-of-node-versions * number-of-tav-modules exceed the GitHub limit of 256? Currently we are at 245. If we pass the limit, then we'll need to cope somehow. See https://github.com/elastic/apm-agent-nodejs/pull/3127#issuecomment-1487213047
- [x] The "dev-utils/jenkins-build-slow-steps.sh" dev tool should be replaced with one that looks at the GH Action runs. See https://github.com/elastic/apm-agent-nodejs/pull/3127#issuecomment-1487497306 for a start.

/cc @v1v (Victor, I'm not suggesting *you* need to do these things. I'll do some of them. Mostly I would appreciate suggestions/advice on the first item.)

**Comment by trentm** [comment]
> To add more clarity, there are some caveats, for instance, GitHub comments should trigger builds if they are coming from an Elastician user ...

Note that I'm fine if there isn't a way to start this via a GitHub PR comment. For example if it is a separate `gh ...` command that would be fine to start. E.g. `gh workflow run tav.yml --ref trentm/my-feature-branch -f node=16 -f module=fastify`


> likely some of the existing degraded issues that happened today...

Yah, hopefully. We'll see in coming days.

**Comment by v1v** [comment]
https://github.com/elastic-robots/gh-actions-interactions/blob/main/.github/workflows/ci-command.yml is the minimal proposal to use GitHub commands

1) https://github.com/elastic-robots/gh-actions-interactions/pull/1#issuecomment-1490561979 is the comment to trigger the above with a reaction 👀 
2) https://github.com/elastic-robots/gh-actions-interactions/pull/1#issuecomment-1490562281 is the comment if not supported for that particular user (aka no write/admin permissions in the repo)
3) https://github.com/elastic-robots/gh-actions-interactions/pull/1#issuecomment-1490576454 is the comment with the reaction 👍 when things worked like a charm

Tasks:

- [ ] Create GitHub check with the link to the GitHub run
- [ ] Create customisable github commands `/test module module1,module2,module3` or `/test module module1,module2 in 1.16` or `/test module all`

What are your thoughts?

**Comment by trentm** [comment]
This looks great.

1. We have a separate discussion on the trigger condition.
2. Can we use `/test tav ...` to have the name "tav" in use, rather than `module`, please?
3. Also, *potentially* it would be nice to be able to select a subset of the node versions. `/test tav redis,ioredis 19,20`. But that can come later.
4. Next is to figure out how to select from the "tav.yml" matrix with these inputs.

**Comment by v1v** [comment]
https://github.com/elastic/apm-agent-nodejs/pull/3246 is the one supporting running tav modules individually as discussed in https://github.com/elastic/apm-agent-nodejs/issues/3227#issuecomment-1490634041

**Comment by trentm** [comment]
A follow-up on #3232.

An issue with using `issue_comment` as the workflow trigger is that -- according to https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#issue_comment and according to my testing -- has the GITHUB_REF associated with the default branch and not associated with the PR branch. The github.event. object does not have a .pull_request object from which to pull a .head.sha of the latest current commit to that branch. An example issue_comment event payload is here: https://gist.github.com/trentm/17c6a29cf76fdad725e2b119c80a0c36

From a separate discussion some alternative ideas:

> 
>     1. Continue to use the `issue_comment` workflow trigger. Have code that calls the GH API to get the latest commit on the PR _before_ the `github.event.comment.created_at` time. This feels a little complex, but I think it should work. (Another issue with using `issue_comment` is that the result of the workflow does _not_ result in GitHub _Checks_ being added to the PR to show whether the TAV tests pass. We would perhaps also need to add usage of the GitHub Checks API to add results.)
> 
>     2. Investigate using [the `pull_request_review_comment` event](https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#pull_request_review_comment) to trigger this workflow. IIUC, this is associated with the current PR commit, so might work much better. It _does_ mean the repo maintainers would need to use the PR review UI for the `/test tav` trigger comment, but that should be fine.

I played around a little more. The event we can use here is actually `pull_request_review` (type=submitted). This triggers for any review on a PR. The good thing here is that it is associated with a particular commit on the PR, this means it will test with the commit that was reviewed and there will be GitHub checks progress when using it. Here are a couple screenshots showing that GitHub Checks progress:

![Screenshot 2023-04-10 at 2 19 12 PM](https://user-images.githubusercontent.com/46866/231002326-32eab654-3a95-400c-a0d7-b4fbd796b15d.png)

![Screenshot 2023-04-10 at 2 20 29 PM](https://user-images.githubusercontent.com/46866/231002364-aaaa6aef-35a1-4f5e-904b-8b5ad598b548.png)


Here is a starter "tav-command.yml" used for the above examples:

```yaml
# Dev notes:
# - An edge case: When I was adding a pull request review for a commit, and
#   a new commit was added to the PR before I submitted it... this did *NOT*
#   result in a `pull_request_review` event. So I guess a "/test tav" will not
#   happen for non-latest commit on the PR. I can live with that.

name: tav-command

on:
  pull_request_review:
    types: [submitted]

# XXX Do we need both of these permissions any more? Because the GitHub checks
#     UI shows progress, we don't need reactions anymore, I don't think.
# permissions:
#   contents: write
#   pull-requests: write

jobs:
  command-validation:
    runs-on: ubuntu-latest
    if: startsWith(github.event.review.body, '/test tav')
    steps:
    - name: XXX Dump GitHub context
      env:
        GITHUB_CONTEXT: ${{ toJson(github) }}
      run: |
        echo "$GITHUB_CONTEXT"

    # XXX This does NOT work on the pull_request_review event data. We will need to support that.
    # - name: Validate github comment
    #   uses: elastic/apm-pipeline-library/.github/actions/validate-github-comment@current

    - uses: actions/checkout@v3
    - run: echo "..."
```
