### ISSUE TITLE
Error payload in addErrorFilter does not contain HTTP response metadata

### ISSUE THREAD

**Issue by phenrique-godaddy** [elastic/apm-agent-nodejs#3487]
**Describe the bug**

I am using serverless with APM, and trying to use `apm.addErrorFilter` to filter out requests with status_code >= 500 of my APM server. However the metadata about the HTTP response is unavailable:

![image](https://github.com/elastic/apm-agent-nodejs/assets/112900532/65b7308b-f45c-4983-89ad-95d8ae08d19b) 

**To Reproduce**

1. Using this AWS config:

```yml
provider:
  name: aws
  runtime: 'nodejs18.x'
  timeout: 30
  apiGateway:
    shouldStartNameWithService: true
  stage: 'local'
  scProductName: ServerlessLambda
  scProductVersion: '5.0.0'
  region: us-west-2
  environment:
    NODE_OPTIONS: '-r elastic-apm-node/start'
    ELASTIC_APM_LAMBDA_APM_SERVER: ${env:APM_SERVER_URL, ''}
    ELASTIC_APM_SECRET_TOKEN: ${env:APM_SECRET_TOKEN, ''}
```
2. Add `apm.addErrorFilter` and log it:

```ts
apm.addErrorFilter((payload) => {
  logger.info(`payload: ${JSON.stringify(payload)}`);
  return payload;
});
```

3. Make a request that returns >= 400

4. Check the error in APM errors or the logs of the application. Response metadata is unavailable.

**Expected behavior**

I'm expecting to find the metadata of the HTTP response.

**Environment*

- OS: Linux 22.04.1
- Node.js version: 18.16.1
- APM Server version: 7.17.6
- Agent version: 3.48.0

**How are you starting the agent?**

- [ ] Calling `agent.start()` directly (e.g. `require('elastic-apm-node').start(...)`)
- [ ] Requiring `elastic-apm-node/start` from within the source code
- [x] Starting node with `-r elastic-apm-node/start`

**Additional context**

If I use `apm.addTransactionFilter`, the payload actually has the result of the HTTP request in `"HTTP 2xx"` format, as the doc mentions. It's only for the error filter that it does not seem to work.

Agent config options: 
<details>
  <summary>Click to expand</summary>

```yml
  environment:
    NODE_OPTIONS: '-r elastic-apm-node/start'
    ELASTIC_APM_LAMBDA_APM_SERVER: ${env:APM_SERVER_URL, ''}
    ELASTIC_APM_SECRET_TOKEN: ${env:APM_SECRET_TOKEN, ''}
```
</details>

`package.json` dependencies:
<details>
  <summary>Click to expand</summary>

```json
{
    "@elastic/ecs-winston-format": "^1.3.1",
    "@pothos/core": "^3.10.1",
    "apollo-server-lambda": "^3.6.7",
    "dataloader": "^2.1.0",
    "dynamoose": "^3.0.3",
    "express-async-handler": "^1.2.0",
    "graphql": "^16.3.0",
    "ksuid": "^3.0.0",
    "pothos": "^0.0.1",
    "serverless-http": "^3.0.2",
    "uuid": "^8.3.2",
    "winston": "^3.8.2",
    "@aws-sdk/client-secrets-manager": "^3.363.0",
    "@graphql-eslint/eslint-plugin": "^3.10.3",
    "@serverless/compose": "^1.2.3",
    "@swc/core": "^1.3.1",
    "@swc/jest": "^0.2.22",
    "elastic-apm-node": "^3.48.0",
    "graphql-scalars": "^1.17.0",
    "graphql-type-json": "^0.3.2",
    "nock": "^13.3.0",
    "serverless-aws-servicecatalog": "^2.1.0",
    "serverless-esbuild": "^1.27.0",
    "serverless-offline": "^12.0.3",
    "ts-node": "^10.7.0",
    "turbo": "^1.5.5",
    "typescript": "^4.8.4"
  }
```
</details>
