### ISSUE TITLE
test issue to see if labeler action works on an issue

### ISSUE THREAD

**Issue by trentm** [elastic/apm-agent-nodejs#3920]
... rather than on a PR. I'm sanity testing the permissions that https://docs.github.com/en/rest/issues/labels?apiVersion=2022-11-28#add-labels-to-an-issue says it needs.

Refs: https://github.com/elastic/apm-agent-nodejs/issues/3884

**Comment by trentm** [comment]
Yup, works. That's because the workflow file (https://github.com/elastic/apm-agent-nodejs/actions/runs/8335623705/workflow) has:

```
# 'issues: write' for https://docs.github.com/en/rest/issues/labels?apiVersion=2022-11-28#add-labels-to-an-issue
permissions:
  contents: read
  issues: write
```

Because I interpreted these docs:

> The token must have at least one of the following permission sets:
>
>    issues:write
>    pull_requests:write

to mean that either permission would work. However, you need the one for adding a label to issues and the other to add to PRs. Perhaps this was obvious to all others.
